### ISSUE TITLE
[Bug] No colors

### ISSUE THREAD

**Issue by jerviscui** [neiderruiz/vs-code-capture-code#1]
![image](https://github.com/neiderruiz/vs-code-capture-code/assets/6396748/43329716-9a28-4f12-9a88-1fb49cdf8601)

**Comment by neiderruiz** [comment]
Hi! @jerviscui  What programming languages ​​are you using to add them?

I added rust, thanks for your suggestion.

![download](https://github.com/neiderruiz/vs-code-capture-code/assets/57574910/02a05cf2-f725-4eae-811c-bf31a91021b4)
